[package]
name = "kami"
version = "0.1.0"
authors = ["Justin Stanley"]
edition = "2018"

[dependencies]
clap = "2.33.3"
dirs = "3.0.1"
log = "0.4"
pretty_env_logger = "0.3"
tensorflow = { version = "0.16.1", features = ["tensorflow_gpu"] }