[package]
name = "kami"
version = "0.1.0"
authors = ["Justin Stanley"]
edition = "2018"

[dependencies]
clap = "2.33.3"
config = "0.11.0"
dirs = "3.0.1"
futures = "0.3.14"
log = "0.4"
pretty_env_logger = "0.3"
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "3a7559edcec7c443e68e22e038aaa2d90ef27c23" }
tensorflow = { version = "0.16.1", features = ["tensorflow_gpu"] }