[package]
name    = "kami-search"
version = "0.1.0"
edition = "2018"
authors = ["Justin Stanley"]

[dependencies]
chess = "3.2.0"
rand = "0.6.5"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
tch = "0.5.0"
